<a href="<?php echo $this->auth_url; ?>">Test</a>

<form id="get_location_form" action="#" method="post">

	<table>
		<tr>
			<th>Latitude:</th>
			<td><input type="text" name="cur_loc_lat" id="cur_loc_lat" maxlength="40" class="search_param point" /></td>
		</tr>
		<tr>
			<th>Longitude:</th>
			<td><input type="text" name="cur_loc_lon" id="cur_loc_lon" maxlength="40" class="search_param point" /></td>
		</tr>	
	</table>

	<table>
		<tr>
			<th>Address:</th>
			<td><input type="text" name="cur_address_1" id="cur_address_1" maxlength="40" class="search_param local" /></td>
			<td><input type="text" name="cur_address_2" id="cur_address_2" maxlength="40" class="search_param local" /></td>
		</tr>
		<tr>
			<th>City:</th>
			<td colspan="2"><input type="text" name="cur_city" id="cur_city" maxlength="40" class="search_param local" /></td>
		</tr>
		<tr>
			<th>State:</th>
			<td colspan="2">
				<select id="cur_state" name="cur_state" class="search_param local">
					<?php echo $this->statesList; ?>
				</select>
			</td>
		</tr>		
	</table>
	
	<input type="submit" id="submit" name="submit" value="Submit" />
</form>

<script>
$(function(){
	$('#get_location_form').submit(function() {
		search();
		return false;
	});

	/*FILTER ALL INPUTS BEFORE POST*/
    $('.point').bind('input', function() {
    	$(this).val($(this).val().replace(/[^0-9.-]/gi, ''));
    });	

    $('.local').bind('input', function() {
    	$(this).val($(this).val().replace(/[^a-z0-9,. '-]/gi, ''));
    });	
    
	function search() {
		$.ajax({
			url:"/search/ajaxsearch",
			type:"POST",
			data:$(".search_param").serialize(),
			success: function(msg) {
				console.log(msg);
			} 
		});
	}
});
</script>
