
<h2>Search images by location.</h2>

<form id="get_location_form" action="#" method="post">

	<fieldset>
		<legend>Enter your lat/lng:</legend>
		<table>
			<tr>
				<th>Latitude:</th>
				<td><input type="text" name="cur_loc_lat" id="cur_loc_lat" maxlength="40" class="search_param point" /></td>
			</tr>
			<tr>
				<th>Longitude:</th>
				<td><input type="text" name="cur_loc_lon" id="cur_loc_lon" maxlength="40" class="search_param point" /></td>
			</tr>	
		</table>
		<input type="hidden" class="search_param" name="acc_token" id="acc_token" value="<?php echo $_SESSION['access_token']; ?>" />
	</fieldset>

	<input type="button" id="get_location" name="get_location" value="Get My Location" />
	<input type="submit" id="submit" name="submit" value="Submit" />
</form>

<div id="local_image_list"></div>
<div id="map_canvas" style="width:100%;height:100%;"></div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/search.js"></script>